#ifndef __GLMOCK_HPP__
#define __GLMOCK_HPP__

#include <gmock/gmock.h>

#include <GL/glew.h>

class GlMock {
public:
    GlMock();
    ~GlMock();
    MOCK_METHOD2( gl_Accum, void (GLenum op, GLfloat value) );
    MOCK_METHOD2( gl_AlphaFunc, void (GLenum func, GLclampf ref) );
    MOCK_METHOD3( gl_AreTexturesResident, GLboolean (GLsizei n, const GLuint * textures, GLboolean * residences) );
    MOCK_METHOD1( gl_ArrayElement, void (GLint i) );
    MOCK_METHOD1( gl_Begin, void (GLenum mode) );
    MOCK_METHOD2( gl_BindTexture, void (GLenum target, GLuint texture) );
    MOCK_METHOD7( gl_Bitmap, void (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap) );
    MOCK_METHOD2( gl_BlendFunc, void (GLenum sfactor, GLenum dfactor) );
    MOCK_METHOD1( gl_CallList, void (GLuint list) );
    MOCK_METHOD3( gl_CallLists, void (GLsizei n, GLenum type, const GLvoid * lists) );
    MOCK_METHOD1( gl_Clear, void (GLbitfield mask) );
    MOCK_METHOD4( gl_ClearAccum, void (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) );
    MOCK_METHOD4( gl_ClearColor, void (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) );
    MOCK_METHOD1( gl_ClearDepth, void (GLclampd depth) );
    MOCK_METHOD1( gl_ClearIndex, void (GLfloat c) );
    MOCK_METHOD1( gl_ClearStencil, void (GLint s) );
    MOCK_METHOD2( gl_ClipPlane, void (GLenum plane, const GLdouble * equation) );
    MOCK_METHOD3( gl_Color3b, void (GLbyte red, GLbyte green, GLbyte blue) );
    MOCK_METHOD1( gl_Color3bv, void (const GLbyte * v) );
    MOCK_METHOD3( gl_Color3d, void (GLdouble red, GLdouble green, GLdouble blue) );
    MOCK_METHOD1( gl_Color3dv, void (const GLdouble * v) );
    MOCK_METHOD3( gl_Color3f, void (GLfloat red, GLfloat green, GLfloat blue) );
    MOCK_METHOD1( gl_Color3fv, void (const GLfloat * v) );
    MOCK_METHOD3( gl_Color3i, void (GLint red, GLint green, GLint blue) );
    MOCK_METHOD1( gl_Color3iv, void (const GLint * v) );
    MOCK_METHOD3( gl_Color3s, void (GLshort red, GLshort green, GLshort blue) );
    MOCK_METHOD1( gl_Color3sv, void (const GLshort * v) );
    MOCK_METHOD3( gl_Color3ub, void (GLubyte red, GLubyte green, GLubyte blue) );
    MOCK_METHOD1( gl_Color3ubv, void (const GLubyte * v) );
    MOCK_METHOD3( gl_Color3ui, void (GLuint red, GLuint green, GLuint blue) );
    MOCK_METHOD1( gl_Color3uiv, void (const GLuint * v) );
    MOCK_METHOD3( gl_Color3us, void (GLushort red, GLushort green, GLushort blue) );
    MOCK_METHOD1( gl_Color3usv, void (const GLushort * v) );
    MOCK_METHOD4( gl_Color4b, void (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha) );
    MOCK_METHOD1( gl_Color4bv, void (const GLbyte * v) );
    MOCK_METHOD4( gl_Color4d, void (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha) );
    MOCK_METHOD1( gl_Color4dv, void (const GLdouble * v) );
    MOCK_METHOD4( gl_Color4f, void (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) );
    MOCK_METHOD1( gl_Color4fv, void (const GLfloat * v) );
    MOCK_METHOD4( gl_Color4i, void (GLint red, GLint green, GLint blue, GLint alpha) );
    MOCK_METHOD1( gl_Color4iv, void (const GLint * v) );
    MOCK_METHOD4( gl_Color4s, void (GLshort red, GLshort green, GLshort blue, GLshort alpha) );
    MOCK_METHOD1( gl_Color4sv, void (const GLshort * v) );
    MOCK_METHOD4( gl_Color4ub, void (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha) );
    MOCK_METHOD1( gl_Color4ubv, void (const GLubyte * v) );
    MOCK_METHOD4( gl_Color4ui, void (GLuint red, GLuint green, GLuint blue, GLuint alpha) );
    MOCK_METHOD1( gl_Color4uiv, void (const GLuint * v) );
    MOCK_METHOD4( gl_Color4us, void (GLushort red, GLushort green, GLushort blue, GLushort alpha) );
    MOCK_METHOD1( gl_Color4usv, void (const GLushort * v) );
    MOCK_METHOD4( gl_ColorMask, void (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) );
    MOCK_METHOD2( gl_ColorMaterial, void (GLenum face, GLenum mode) );
    MOCK_METHOD4( gl_ColorPointer, void (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD5( gl_CopyPixels, void (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type) );
    MOCK_METHOD7( gl_CopyTexImage1D, void (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border) );
    MOCK_METHOD8( gl_CopyTexImage2D, void (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) );
    MOCK_METHOD6( gl_CopyTexSubImage1D, void (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width) );
    MOCK_METHOD8( gl_CopyTexSubImage2D, void (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) );
    MOCK_METHOD1( gl_CullFace, void (GLenum mode) );
    MOCK_METHOD2( gl_DeleteLists, void (GLuint list, GLsizei range) );
    MOCK_METHOD2( gl_DeleteTextures, void (GLsizei n, const GLuint * textures) );
    MOCK_METHOD1( gl_DepthFunc, void (GLenum func) );
    MOCK_METHOD1( gl_DepthMask, void (GLboolean flag) );
    MOCK_METHOD2( gl_DepthRange, void (GLclampd zNear, GLclampd zFar) );
    MOCK_METHOD1( gl_Disable, void (GLenum cap) );
    MOCK_METHOD1( gl_DisableClientState, void (GLenum array) );
    MOCK_METHOD3( gl_DrawArrays, void (GLenum mode, GLint first, GLsizei count) );
    MOCK_METHOD1( gl_DrawBuffer, void (GLenum mode) );
    MOCK_METHOD4( gl_DrawElements, void (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices) );
    MOCK_METHOD5( gl_DrawPixels, void (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels) );
    MOCK_METHOD1( gl_EdgeFlag, void (GLboolean flag) );
    MOCK_METHOD2( gl_EdgeFlagPointer, void (GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD1( gl_EdgeFlagv, void (const GLboolean * flag) );
    MOCK_METHOD1( gl_Enable, void (GLenum cap) );
    MOCK_METHOD1( gl_EnableClientState, void (GLenum array) );
    MOCK_METHOD0( gl_End, void () );
    MOCK_METHOD0( gl_EndList, void () );
    MOCK_METHOD1( gl_EvalCoord1d, void (GLdouble u) );
    MOCK_METHOD1( gl_EvalCoord1dv, void (const GLdouble * u) );
    MOCK_METHOD1( gl_EvalCoord1f, void (GLfloat u) );
    MOCK_METHOD1( gl_EvalCoord1fv, void (const GLfloat * u) );
    MOCK_METHOD2( gl_EvalCoord2d, void (GLdouble u, GLdouble v) );
    MOCK_METHOD1( gl_EvalCoord2dv, void (const GLdouble * u) );
    MOCK_METHOD2( gl_EvalCoord2f, void (GLfloat u, GLfloat v) );
    MOCK_METHOD1( gl_EvalCoord2fv, void (const GLfloat * u) );
    MOCK_METHOD3( gl_EvalMesh1, void (GLenum mode, GLint i1, GLint i2) );
    MOCK_METHOD5( gl_EvalMesh2, void (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2) );
    MOCK_METHOD1( gl_EvalPoint1, void (GLint i) );
    MOCK_METHOD2( gl_EvalPoint2, void (GLint i, GLint j) );
    MOCK_METHOD3( gl_FeedbackBuffer, void (GLsizei size, GLenum type, GLfloat * buffer) );
    MOCK_METHOD0( gl_Finish, void () );
    MOCK_METHOD0( gl_Flush, void () );
    MOCK_METHOD2( gl_Fogf, void (GLenum pname, GLfloat param) );
    MOCK_METHOD2( gl_Fogfv, void (GLenum pname, const GLfloat * params) );
    MOCK_METHOD2( gl_Fogi, void (GLenum pname, GLint param) );
    MOCK_METHOD2( gl_Fogiv, void (GLenum pname, const GLint * params) );
    MOCK_METHOD1( gl_FrontFace, void (GLenum mode) );
    MOCK_METHOD6( gl_Frustum, void (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar) );
    MOCK_METHOD1( gl_GenLists, GLuint (GLsizei range) );
    MOCK_METHOD2( gl_GenTextures, void (GLsizei n, GLuint * textures) );
    MOCK_METHOD2( gl_GetBooleanv, void (GLenum pname, GLboolean * params) );
    MOCK_METHOD2( gl_GetClipPlane, void (GLenum plane, GLdouble * equation) );
    MOCK_METHOD2( gl_GetDoublev, void (GLenum pname, GLdouble * params) );
    MOCK_METHOD0( gl_GetError, GLenum () );
    MOCK_METHOD2( gl_GetFloatv, void (GLenum pname, GLfloat * params) );
    MOCK_METHOD2( gl_GetIntegerv, void (GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetLightfv, void (GLenum light, GLenum pname, GLfloat * params) );
    MOCK_METHOD3( gl_GetLightiv, void (GLenum light, GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetMapdv, void (GLenum target, GLenum query, GLdouble * v) );
    MOCK_METHOD3( gl_GetMapfv, void (GLenum target, GLenum query, GLfloat * v) );
    MOCK_METHOD3( gl_GetMapiv, void (GLenum target, GLenum query, GLint * v) );
    MOCK_METHOD3( gl_GetMaterialfv, void (GLenum face, GLenum pname, GLfloat * params) );
    MOCK_METHOD3( gl_GetMaterialiv, void (GLenum face, GLenum pname, GLint * params) );
    MOCK_METHOD2( gl_GetPixelMapfv, void (GLenum map, GLfloat * values) );
    MOCK_METHOD2( gl_GetPixelMapuiv, void (GLenum map, GLuint * values) );
    MOCK_METHOD2( gl_GetPixelMapusv, void (GLenum map, GLushort * values) );
    MOCK_METHOD2( gl_GetPointerv, void (GLenum pname, GLvoid ** params) );
    MOCK_METHOD1( gl_GetPolygonStipple, void (GLubyte * mask) );
    MOCK_METHOD1( gl_GetString, const GLubyte * (GLenum name) );
    MOCK_METHOD3( gl_GetTexEnvfv, void (GLenum target, GLenum pname, GLfloat * params) );
    MOCK_METHOD3( gl_GetTexEnviv, void (GLenum target, GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetTexGendv, void (GLenum coord, GLenum pname, GLdouble * params) );
    MOCK_METHOD3( gl_GetTexGenfv, void (GLenum coord, GLenum pname, GLfloat * params) );
    MOCK_METHOD3( gl_GetTexGeniv, void (GLenum coord, GLenum pname, GLint * params) );
    MOCK_METHOD5( gl_GetTexImage, void (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels) );
    MOCK_METHOD4( gl_GetTexLevelParameterfv, void (GLenum target, GLint level, GLenum pname, GLfloat * params) );
    MOCK_METHOD4( gl_GetTexLevelParameteriv, void (GLenum target, GLint level, GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetTexParameterfv, void (GLenum target, GLenum pname, GLfloat * params) );
    MOCK_METHOD3( gl_GetTexParameteriv, void (GLenum target, GLenum pname, GLint * params) );
    MOCK_METHOD2( gl_Hint, void (GLenum target, GLenum mode) );
    MOCK_METHOD1( gl_IndexMask, void (GLuint mask) );
    MOCK_METHOD3( gl_IndexPointer, void (GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD1( gl_Indexd, void (GLdouble c) );
    MOCK_METHOD1( gl_Indexdv, void (const GLdouble * c) );
    MOCK_METHOD1( gl_Indexf, void (GLfloat c) );
    MOCK_METHOD1( gl_Indexfv, void (const GLfloat * c) );
    MOCK_METHOD1( gl_Indexi, void (GLint c) );
    MOCK_METHOD1( gl_Indexiv, void (const GLint * c) );
    MOCK_METHOD1( gl_Indexs, void (GLshort c) );
    MOCK_METHOD1( gl_Indexsv, void (const GLshort * c) );
    MOCK_METHOD1( gl_Indexub, void (GLubyte c) );
    MOCK_METHOD1( gl_Indexubv, void (const GLubyte * c) );
    MOCK_METHOD0( gl_InitNames, void () );
    MOCK_METHOD3( gl_InterleavedArrays, void (GLenum format, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD1( gl_IsEnabled, GLboolean (GLenum cap) );
    MOCK_METHOD1( gl_IsList, GLboolean (GLuint list) );
    MOCK_METHOD1( gl_IsTexture, GLboolean (GLuint texture) );
    MOCK_METHOD2( gl_LightModelf, void (GLenum pname, GLfloat param) );
    MOCK_METHOD2( gl_LightModelfv, void (GLenum pname, const GLfloat * params) );
    MOCK_METHOD2( gl_LightModeli, void (GLenum pname, GLint param) );
    MOCK_METHOD2( gl_LightModeliv, void (GLenum pname, const GLint * params) );
    MOCK_METHOD3( gl_Lightf, void (GLenum light, GLenum pname, GLfloat param) );
    MOCK_METHOD3( gl_Lightfv, void (GLenum light, GLenum pname, const GLfloat * params) );
    MOCK_METHOD3( gl_Lighti, void (GLenum light, GLenum pname, GLint param) );
    MOCK_METHOD3( gl_Lightiv, void (GLenum light, GLenum pname, const GLint * params) );
    MOCK_METHOD2( gl_LineStipple, void (GLint factor, GLushort pattern) );
    MOCK_METHOD1( gl_LineWidth, void (GLfloat width) );
    MOCK_METHOD1( gl_ListBase, void (GLuint base) );
    MOCK_METHOD0( gl_LoadIdentity, void () );
    MOCK_METHOD1( gl_LoadMatrixd, void (const GLdouble * m) );
    MOCK_METHOD1( gl_LoadMatrixf, void (const GLfloat * m) );
    MOCK_METHOD1( gl_LoadName, void (GLuint name) );
    MOCK_METHOD1( gl_LogicOp, void (GLenum opcode) );
    MOCK_METHOD6( gl_Map1d, void (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points) );
    MOCK_METHOD6( gl_Map1f, void (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points) );
    MOCK_METHOD10( gl_Map2d, void (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points) );
    MOCK_METHOD10( gl_Map2f, void (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points) );
    MOCK_METHOD3( gl_MapGrid1d, void (GLint un, GLdouble u1, GLdouble u2) );
    MOCK_METHOD3( gl_MapGrid1f, void (GLint un, GLfloat u1, GLfloat u2) );
    MOCK_METHOD6( gl_MapGrid2d, void (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2) );
    MOCK_METHOD6( gl_MapGrid2f, void (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2) );
    MOCK_METHOD3( gl_Materialf, void (GLenum face, GLenum pname, GLfloat param) );
    MOCK_METHOD3( gl_Materialfv, void (GLenum face, GLenum pname, const GLfloat * params) );
    MOCK_METHOD3( gl_Materiali, void (GLenum face, GLenum pname, GLint param) );
    MOCK_METHOD3( gl_Materialiv, void (GLenum face, GLenum pname, const GLint * params) );
    MOCK_METHOD1( gl_MatrixMode, void (GLenum mode) );
    MOCK_METHOD1( gl_MultMatrixd, void (const GLdouble * m) );
    MOCK_METHOD1( gl_MultMatrixf, void (const GLfloat * m) );
    MOCK_METHOD2( gl_NewList, void (GLuint list, GLenum mode) );
    MOCK_METHOD3( gl_Normal3b, void (GLbyte nx, GLbyte ny, GLbyte nz) );
    MOCK_METHOD1( gl_Normal3bv, void (const GLbyte * v) );
    MOCK_METHOD3( gl_Normal3d, void (GLdouble nx, GLdouble ny, GLdouble nz) );
    MOCK_METHOD1( gl_Normal3dv, void (const GLdouble * v) );
    MOCK_METHOD3( gl_Normal3f, void (GLfloat nx, GLfloat ny, GLfloat nz) );
    MOCK_METHOD1( gl_Normal3fv, void (const GLfloat * v) );
    MOCK_METHOD3( gl_Normal3i, void (GLint nx, GLint ny, GLint nz) );
    MOCK_METHOD1( gl_Normal3iv, void (const GLint * v) );
    MOCK_METHOD3( gl_Normal3s, void (GLshort nx, GLshort ny, GLshort nz) );
    MOCK_METHOD1( gl_Normal3sv, void (const GLshort * v) );
    MOCK_METHOD3( gl_NormalPointer, void (GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD6( gl_Ortho, void (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar) );
    MOCK_METHOD1( gl_PassThrough, void (GLfloat token) );
    MOCK_METHOD3( gl_PixelMapfv, void (GLenum map, GLsizei mapsize, const GLfloat * values) );
    MOCK_METHOD3( gl_PixelMapuiv, void (GLenum map, GLsizei mapsize, const GLuint * values) );
    MOCK_METHOD3( gl_PixelMapusv, void (GLenum map, GLsizei mapsize, const GLushort * values) );
    MOCK_METHOD2( gl_PixelStoref, void (GLenum pname, GLfloat param) );
    MOCK_METHOD2( gl_PixelStorei, void (GLenum pname, GLint param) );
    MOCK_METHOD2( gl_PixelTransferf, void (GLenum pname, GLfloat param) );
    MOCK_METHOD2( gl_PixelTransferi, void (GLenum pname, GLint param) );
    MOCK_METHOD2( gl_PixelZoom, void (GLfloat xfactor, GLfloat yfactor) );
    MOCK_METHOD1( gl_PointSize, void (GLfloat size) );
    MOCK_METHOD2( gl_PolygonMode, void (GLenum face, GLenum mode) );
    MOCK_METHOD2( gl_PolygonOffset, void (GLfloat factor, GLfloat units) );
    MOCK_METHOD1( gl_PolygonStipple, void (const GLubyte * mask) );
    MOCK_METHOD0( gl_PopAttrib, void () );
    MOCK_METHOD0( gl_PopClientAttrib, void () );
    MOCK_METHOD0( gl_PopMatrix, void () );
    MOCK_METHOD0( gl_PopName, void () );
    MOCK_METHOD3( gl_PrioritizeTextures, void (GLsizei n, const GLuint * textures, const GLclampf * priorities) );
    MOCK_METHOD1( gl_PushAttrib, void (GLbitfield mask) );
    MOCK_METHOD1( gl_PushClientAttrib, void (GLbitfield mask) );
    MOCK_METHOD0( gl_PushMatrix, void () );
    MOCK_METHOD1( gl_PushName, void (GLuint name) );
    MOCK_METHOD2( gl_RasterPos2d, void (GLdouble x, GLdouble y) );
    MOCK_METHOD1( gl_RasterPos2dv, void (const GLdouble * v) );
    MOCK_METHOD2( gl_RasterPos2f, void (GLfloat x, GLfloat y) );
    MOCK_METHOD1( gl_RasterPos2fv, void (const GLfloat * v) );
    MOCK_METHOD2( gl_RasterPos2i, void (GLint x, GLint y) );
    MOCK_METHOD1( gl_RasterPos2iv, void (const GLint * v) );
    MOCK_METHOD2( gl_RasterPos2s, void (GLshort x, GLshort y) );
    MOCK_METHOD1( gl_RasterPos2sv, void (const GLshort * v) );
    MOCK_METHOD3( gl_RasterPos3d, void (GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD1( gl_RasterPos3dv, void (const GLdouble * v) );
    MOCK_METHOD3( gl_RasterPos3f, void (GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD1( gl_RasterPos3fv, void (const GLfloat * v) );
    MOCK_METHOD3( gl_RasterPos3i, void (GLint x, GLint y, GLint z) );
    MOCK_METHOD1( gl_RasterPos3iv, void (const GLint * v) );
    MOCK_METHOD3( gl_RasterPos3s, void (GLshort x, GLshort y, GLshort z) );
    MOCK_METHOD1( gl_RasterPos3sv, void (const GLshort * v) );
    MOCK_METHOD4( gl_RasterPos4d, void (GLdouble x, GLdouble y, GLdouble z, GLdouble w) );
    MOCK_METHOD1( gl_RasterPos4dv, void (const GLdouble * v) );
    MOCK_METHOD4( gl_RasterPos4f, void (GLfloat x, GLfloat y, GLfloat z, GLfloat w) );
    MOCK_METHOD1( gl_RasterPos4fv, void (const GLfloat * v) );
    MOCK_METHOD4( gl_RasterPos4i, void (GLint x, GLint y, GLint z, GLint w) );
    MOCK_METHOD1( gl_RasterPos4iv, void (const GLint * v) );
    MOCK_METHOD4( gl_RasterPos4s, void (GLshort x, GLshort y, GLshort z, GLshort w) );
    MOCK_METHOD1( gl_RasterPos4sv, void (const GLshort * v) );
    MOCK_METHOD1( gl_ReadBuffer, void (GLenum mode) );
    MOCK_METHOD7( gl_ReadPixels, void (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels) );
    MOCK_METHOD4( gl_Rectd, void (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2) );
    MOCK_METHOD2( gl_Rectdv, void (const GLdouble * v1, const GLdouble * v2) );
    MOCK_METHOD4( gl_Rectf, void (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2) );
    MOCK_METHOD2( gl_Rectfv, void (const GLfloat * v1, const GLfloat * v2) );
    MOCK_METHOD4( gl_Recti, void (GLint x1, GLint y1, GLint x2, GLint y2) );
    MOCK_METHOD2( gl_Rectiv, void (const GLint * v1, const GLint * v2) );
    MOCK_METHOD4( gl_Rects, void (GLshort x1, GLshort y1, GLshort x2, GLshort y2) );
    MOCK_METHOD2( gl_Rectsv, void (const GLshort * v1, const GLshort * v2) );
    MOCK_METHOD1( gl_RenderMode, GLint (GLenum mode) );
    MOCK_METHOD4( gl_Rotated, void (GLdouble angle, GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD4( gl_Rotatef, void (GLfloat angle, GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD3( gl_Scaled, void (GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD3( gl_Scalef, void (GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD4( gl_Scissor, void (GLint x, GLint y, GLsizei width, GLsizei height) );
    MOCK_METHOD2( gl_SelectBuffer, void (GLsizei size, GLuint * buffer) );
    MOCK_METHOD1( gl_ShadeModel, void (GLenum mode) );
    MOCK_METHOD3( gl_StencilFunc, void (GLenum func, GLint ref, GLuint mask) );
    MOCK_METHOD1( gl_StencilMask, void (GLuint mask) );
    MOCK_METHOD3( gl_StencilOp, void (GLenum fail, GLenum zfail, GLenum zpass) );
    MOCK_METHOD1( gl_TexCoord1d, void (GLdouble s) );
    MOCK_METHOD1( gl_TexCoord1dv, void (const GLdouble * v) );
    MOCK_METHOD1( gl_TexCoord1f, void (GLfloat s) );
    MOCK_METHOD1( gl_TexCoord1fv, void (const GLfloat * v) );
    MOCK_METHOD1( gl_TexCoord1i, void (GLint s) );
    MOCK_METHOD1( gl_TexCoord1iv, void (const GLint * v) );
    MOCK_METHOD1( gl_TexCoord1s, void (GLshort s) );
    MOCK_METHOD1( gl_TexCoord1sv, void (const GLshort * v) );
    MOCK_METHOD2( gl_TexCoord2d, void (GLdouble s, GLdouble t) );
    MOCK_METHOD1( gl_TexCoord2dv, void (const GLdouble * v) );
    MOCK_METHOD2( gl_TexCoord2f, void (GLfloat s, GLfloat t) );
    MOCK_METHOD1( gl_TexCoord2fv, void (const GLfloat * v) );
    MOCK_METHOD2( gl_TexCoord2i, void (GLint s, GLint t) );
    MOCK_METHOD1( gl_TexCoord2iv, void (const GLint * v) );
    MOCK_METHOD2( gl_TexCoord2s, void (GLshort s, GLshort t) );
    MOCK_METHOD1( gl_TexCoord2sv, void (const GLshort * v) );
    MOCK_METHOD3( gl_TexCoord3d, void (GLdouble s, GLdouble t, GLdouble r) );
    MOCK_METHOD1( gl_TexCoord3dv, void (const GLdouble * v) );
    MOCK_METHOD3( gl_TexCoord3f, void (GLfloat s, GLfloat t, GLfloat r) );
    MOCK_METHOD1( gl_TexCoord3fv, void (const GLfloat * v) );
    MOCK_METHOD3( gl_TexCoord3i, void (GLint s, GLint t, GLint r) );
    MOCK_METHOD1( gl_TexCoord3iv, void (const GLint * v) );
    MOCK_METHOD3( gl_TexCoord3s, void (GLshort s, GLshort t, GLshort r) );
    MOCK_METHOD1( gl_TexCoord3sv, void (const GLshort * v) );
    MOCK_METHOD4( gl_TexCoord4d, void (GLdouble s, GLdouble t, GLdouble r, GLdouble q) );
    MOCK_METHOD1( gl_TexCoord4dv, void (const GLdouble * v) );
    MOCK_METHOD4( gl_TexCoord4f, void (GLfloat s, GLfloat t, GLfloat r, GLfloat q) );
    MOCK_METHOD1( gl_TexCoord4fv, void (const GLfloat * v) );
    MOCK_METHOD4( gl_TexCoord4i, void (GLint s, GLint t, GLint r, GLint q) );
    MOCK_METHOD1( gl_TexCoord4iv, void (const GLint * v) );
    MOCK_METHOD4( gl_TexCoord4s, void (GLshort s, GLshort t, GLshort r, GLshort q) );
    MOCK_METHOD1( gl_TexCoord4sv, void (const GLshort * v) );
    MOCK_METHOD4( gl_TexCoordPointer, void (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD3( gl_TexEnvf, void (GLenum target, GLenum pname, GLfloat param) );
    MOCK_METHOD3( gl_TexEnvfv, void (GLenum target, GLenum pname, const GLfloat * params) );
    MOCK_METHOD3( gl_TexEnvi, void (GLenum target, GLenum pname, GLint param) );
    MOCK_METHOD3( gl_TexEnviv, void (GLenum target, GLenum pname, const GLint * params) );
    MOCK_METHOD3( gl_TexGend, void (GLenum coord, GLenum pname, GLdouble param) );
    MOCK_METHOD3( gl_TexGendv, void (GLenum coord, GLenum pname, const GLdouble * params) );
    MOCK_METHOD3( gl_TexGenf, void (GLenum coord, GLenum pname, GLfloat param) );
    MOCK_METHOD3( gl_TexGenfv, void (GLenum coord, GLenum pname, const GLfloat * params) );
    MOCK_METHOD3( gl_TexGeni, void (GLenum coord, GLenum pname, GLint param) );
    MOCK_METHOD3( gl_TexGeniv, void (GLenum coord, GLenum pname, const GLint * params) );
    MOCK_METHOD8( gl_TexImage1D, void (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels) );
    MOCK_METHOD9( gl_TexImage2D, void (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels) );
    MOCK_METHOD3( gl_TexParameterf, void (GLenum target, GLenum pname, GLfloat param) );
    MOCK_METHOD3( gl_TexParameterfv, void (GLenum target, GLenum pname, const GLfloat * params) );
    MOCK_METHOD3( gl_TexParameteri, void (GLenum target, GLenum pname, GLint param) );
    MOCK_METHOD3( gl_TexParameteriv, void (GLenum target, GLenum pname, const GLint * params) );
    MOCK_METHOD7( gl_TexSubImage1D, void (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels) );
    MOCK_METHOD9( gl_TexSubImage2D, void (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels) );
    MOCK_METHOD3( gl_Translated, void (GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD3( gl_Translatef, void (GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD2( gl_Vertex2d, void (GLdouble x, GLdouble y) );
    MOCK_METHOD1( gl_Vertex2dv, void (const GLdouble * v) );
    MOCK_METHOD2( gl_Vertex2f, void (GLfloat x, GLfloat y) );
    MOCK_METHOD1( gl_Vertex2fv, void (const GLfloat * v) );
    MOCK_METHOD2( gl_Vertex2i, void (GLint x, GLint y) );
    MOCK_METHOD1( gl_Vertex2iv, void (const GLint * v) );
    MOCK_METHOD2( gl_Vertex2s, void (GLshort x, GLshort y) );
    MOCK_METHOD1( gl_Vertex2sv, void (const GLshort * v) );
    MOCK_METHOD3( gl_Vertex3d, void (GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD1( gl_Vertex3dv, void (const GLdouble * v) );
    MOCK_METHOD3( gl_Vertex3f, void (GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD1( gl_Vertex3fv, void (const GLfloat * v) );
    MOCK_METHOD3( gl_Vertex3i, void (GLint x, GLint y, GLint z) );
    MOCK_METHOD1( gl_Vertex3iv, void (const GLint * v) );
    MOCK_METHOD3( gl_Vertex3s, void (GLshort x, GLshort y, GLshort z) );
    MOCK_METHOD1( gl_Vertex3sv, void (const GLshort * v) );
    MOCK_METHOD4( gl_Vertex4d, void (GLdouble x, GLdouble y, GLdouble z, GLdouble w) );
    MOCK_METHOD1( gl_Vertex4dv, void (const GLdouble * v) );
    MOCK_METHOD4( gl_Vertex4f, void (GLfloat x, GLfloat y, GLfloat z, GLfloat w) );
    MOCK_METHOD1( gl_Vertex4fv, void (const GLfloat * v) );
    MOCK_METHOD4( gl_Vertex4i, void (GLint x, GLint y, GLint z, GLint w) );
    MOCK_METHOD1( gl_Vertex4iv, void (const GLint * v) );
    MOCK_METHOD4( gl_Vertex4s, void (GLshort x, GLshort y, GLshort z, GLshort w) );
    MOCK_METHOD1( gl_Vertex4sv, void (const GLshort * v) );
    MOCK_METHOD4( gl_VertexPointer, void (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD4( gl_Viewport, void (GLint x, GLint y, GLsizei width, GLsizei height) );
    MOCK_METHOD1( glu_BeginCurve, void (GLUnurbs * nurb) );
    MOCK_METHOD1( glu_BeginPolygon, void (GLUtesselator * tess) );
    MOCK_METHOD1( glu_BeginSurface, void (GLUnurbs * nurb) );
    MOCK_METHOD1( glu_BeginTrim, void (GLUnurbs * nurb) );
    MOCK_METHOD9( glu_Build1DMipmapLevels, GLint (GLenum target, GLint internalFormat, GLsizei width, GLenum format, GLenum type, GLint level, GLint base, GLint max, const void * data) );
    MOCK_METHOD6( glu_Build1DMipmaps, GLint (GLenum target, GLint internalFormat, GLsizei width, GLenum format, GLenum type, const void * data) );
    MOCK_METHOD10( glu_Build2DMipmapLevels, GLint (GLenum target, GLint internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, GLint level, GLint base, GLint max, const void * data) );
    MOCK_METHOD7( glu_Build2DMipmaps, GLint (GLenum target, GLint internalFormat, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * data) );
    MOCK_METHOD8( glu_Build3DMipmaps, GLint (GLenum target, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * data) );
    MOCK_METHOD2( glu_CheckExtension, GLboolean (const GLubyte * extName, const GLubyte * extString) );
    MOCK_METHOD6( glu_Cylinder, void (GLUquadric * quad, GLdouble base, GLdouble top, GLdouble height, GLint slices, GLint stacks) );
    MOCK_METHOD1( glu_DeleteNurbsRenderer, void (GLUnurbs * nurb) );
    MOCK_METHOD1( glu_DeleteQuadric, void (GLUquadric * quad) );
    MOCK_METHOD1( glu_DeleteTess, void (GLUtesselator * tess) );
    MOCK_METHOD5( glu_Disk, void (GLUquadric * quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops) );
    MOCK_METHOD1( glu_EndCurve, void (GLUnurbs * nurb) );
    MOCK_METHOD1( glu_EndPolygon, void (GLUtesselator * tess) );
    MOCK_METHOD1( glu_EndSurface, void (GLUnurbs * nurb) );
    MOCK_METHOD1( glu_EndTrim, void (GLUnurbs * nurb) );
    MOCK_METHOD1( glu_ErrorString, const GLubyte * (GLenum error) );
    MOCK_METHOD3( glu_GetNurbsProperty, void (GLUnurbs * nurb, GLenum property, GLfloat * data) );
    MOCK_METHOD1( glu_GetString, const GLubyte * (GLenum name) );
    MOCK_METHOD3( glu_GetTessProperty, void (GLUtesselator * tess, GLenum which, GLdouble * data) );
    MOCK_METHOD4( glu_LoadSamplingMatrices, void (GLUnurbs * nurb, const GLfloat * model, const GLfloat * perspective, const GLint * view) );
    MOCK_METHOD9( glu_LookAt, void (GLdouble eyeX, GLdouble eyeY, GLdouble eyeZ, GLdouble centerX, GLdouble centerY, GLdouble centerZ, GLdouble upX, GLdouble upY, GLdouble upZ) );
    MOCK_METHOD0( glu_NewNurbsRenderer, GLUnurbs * () );
    MOCK_METHOD0( glu_NewQuadric, GLUquadric * () );
    MOCK_METHOD0( glu_NewTess, GLUtesselator * () );
    MOCK_METHOD2( glu_NextContour, void (GLUtesselator * tess, GLenum type) );
    MOCK_METHOD3( glu_NurbsCallback, void (GLUnurbs * nurb, GLenum which, _GLUfuncptr CallBackFunc) );
    MOCK_METHOD2( glu_NurbsCallbackData, void (GLUnurbs * nurb, GLvoid * userData) );
    MOCK_METHOD2( glu_NurbsCallbackDataEXT, void (GLUnurbs * nurb, GLvoid * userData) );
    MOCK_METHOD7( glu_NurbsCurve, void (GLUnurbs * nurb, GLint knotCount, GLfloat * knots, GLint stride, GLfloat * control, GLint order, GLenum type) );
    MOCK_METHOD3( glu_NurbsProperty, void (GLUnurbs * nurb, GLenum property, GLfloat value) );
    MOCK_METHOD4( glu_Ortho2D, void (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top) );
    MOCK_METHOD7( glu_PartialDisk, void (GLUquadric * quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops, GLdouble start, GLdouble sweep) );
    MOCK_METHOD4( glu_Perspective, void (GLdouble fovy, GLdouble aspect, GLdouble zNear, GLdouble zFar) );
    MOCK_METHOD5( glu_PickMatrix, void (GLdouble x, GLdouble y, GLdouble delX, GLdouble delY, GLint * viewport) );
    MOCK_METHOD9( glu_Project, GLint (GLdouble objX, GLdouble objY, GLdouble objZ, const GLdouble * model, const GLdouble * proj, const GLint * view, GLdouble * winX, GLdouble * winY, GLdouble * winZ) );
    MOCK_METHOD5( glu_PwlCurve, void (GLUnurbs * nurb, GLint count, GLfloat * data, GLint stride, GLenum type) );
    MOCK_METHOD3( glu_QuadricCallback, void (GLUquadric * quad, GLenum which, _GLUfuncptr CallBackFunc) );
    MOCK_METHOD2( glu_QuadricDrawStyle, void (GLUquadric * quad, GLenum draw) );
    MOCK_METHOD2( glu_QuadricNormals, void (GLUquadric * quad, GLenum normal) );
    MOCK_METHOD2( glu_QuadricOrientation, void (GLUquadric * quad, GLenum orientation) );
    MOCK_METHOD2( glu_QuadricTexture, void (GLUquadric * quad, GLboolean texture) );
    MOCK_METHOD9( glu_ScaleImage, GLint (GLenum format, GLsizei wIn, GLsizei hIn, GLenum typeIn, const void * dataIn, GLsizei wOut, GLsizei hOut, GLenum typeOut, GLvoid * dataOut) );
    MOCK_METHOD4( glu_Sphere, void (GLUquadric * quad, GLdouble radius, GLint slices, GLint stacks) );
    MOCK_METHOD1( glu_TessBeginContour, void (GLUtesselator * tess) );
    MOCK_METHOD2( glu_TessBeginPolygon, void (GLUtesselator * tess, GLvoid * data) );
    MOCK_METHOD3( glu_TessCallback, void (GLUtesselator * tess, GLenum which, _GLUfuncptr CallBackFunc) );
    MOCK_METHOD1( glu_TessEndContour, void (GLUtesselator * tess) );
    MOCK_METHOD1( glu_TessEndPolygon, void (GLUtesselator * tess) );
    MOCK_METHOD4( glu_TessNormal, void (GLUtesselator * tess, GLdouble valueX, GLdouble valueY, GLdouble valueZ) );
    MOCK_METHOD3( glu_TessProperty, void (GLUtesselator * tess, GLenum which, GLdouble data) );
    MOCK_METHOD3( glu_TessVertex, void (GLUtesselator * tess, GLdouble * location, GLvoid * data) );
    MOCK_METHOD9( glu_UnProject, GLint (GLdouble winX, GLdouble winY, GLdouble winZ, const GLdouble * model, const GLdouble * proj, const GLint * view, GLdouble * objX, GLdouble * objY, GLdouble * objZ) );
    MOCK_METHOD9( gl_CopyTexSubImage3D, void  (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height) );
    MOCK_METHOD6( gl_DrawRangeElements, void  (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices) );
    MOCK_METHOD10( gl_TexImage3D, void  (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels) );
    MOCK_METHOD1( gl_ActiveTexture, void  (GLenum texture) );
    MOCK_METHOD1( gl_ClientActiveTexture, void  (GLenum texture) );
    MOCK_METHOD7( gl_CompressedTexImage1D, void  (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data) );
    MOCK_METHOD8( gl_CompressedTexImage2D, void  (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data) );
    MOCK_METHOD9( gl_CompressedTexImage3D, void  (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data) );
    MOCK_METHOD7( gl_CompressedTexSubImage1D, void  (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data) );
    MOCK_METHOD9( gl_CompressedTexSubImage2D, void  (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data) );
    MOCK_METHOD3( gl_GetCompressedTexImage, void  (GLenum target, GLint lod, GLvoid * img) );
    MOCK_METHOD1( gl_LoadTransposeMatrixd, void  (const GLdouble * m) );
    MOCK_METHOD1( gl_LoadTransposeMatrixf, void  (const GLfloat * m) );
    MOCK_METHOD1( gl_MultTransposeMatrixd, void  (const GLdouble * m) );
    MOCK_METHOD1( gl_MultTransposeMatrixf, void  (const GLfloat * m) );
    MOCK_METHOD2( gl_MultiTexCoord1d, void  (GLenum target, GLdouble s) );
    MOCK_METHOD2( gl_MultiTexCoord1dv, void  (GLenum target, const GLdouble * v) );
    MOCK_METHOD2( gl_MultiTexCoord1f, void  (GLenum target, GLfloat s) );
    MOCK_METHOD2( gl_MultiTexCoord1fv, void  (GLenum target, const GLfloat * v) );
    MOCK_METHOD2( gl_MultiTexCoord1i, void  (GLenum target, GLint s) );
    MOCK_METHOD2( gl_MultiTexCoord1iv, void  (GLenum target, const GLint * v) );
    MOCK_METHOD2( gl_MultiTexCoord1s, void  (GLenum target, GLshort s) );
    MOCK_METHOD2( gl_MultiTexCoord1sv, void  (GLenum target, const GLshort * v) );
    MOCK_METHOD3( gl_MultiTexCoord2d, void  (GLenum target, GLdouble s, GLdouble t) );
    MOCK_METHOD2( gl_MultiTexCoord2dv, void  (GLenum target, const GLdouble * v) );
    MOCK_METHOD3( gl_MultiTexCoord2f, void  (GLenum target, GLfloat s, GLfloat t) );
    MOCK_METHOD2( gl_MultiTexCoord2fv, void  (GLenum target, const GLfloat * v) );
    MOCK_METHOD3( gl_MultiTexCoord2i, void  (GLenum target, GLint s, GLint t) );
    MOCK_METHOD2( gl_MultiTexCoord2iv, void  (GLenum target, const GLint * v) );
    MOCK_METHOD3( gl_MultiTexCoord2s, void  (GLenum target, GLshort s, GLshort t) );
    MOCK_METHOD2( gl_MultiTexCoord2sv, void  (GLenum target, const GLshort * v) );
    MOCK_METHOD4( gl_MultiTexCoord3d, void  (GLenum target, GLdouble s, GLdouble t, GLdouble r) );
    MOCK_METHOD2( gl_MultiTexCoord3dv, void  (GLenum target, const GLdouble * v) );
    MOCK_METHOD4( gl_MultiTexCoord3f, void  (GLenum target, GLfloat s, GLfloat t, GLfloat r) );
    MOCK_METHOD2( gl_MultiTexCoord3fv, void  (GLenum target, const GLfloat * v) );
    MOCK_METHOD4( gl_MultiTexCoord3i, void  (GLenum target, GLint s, GLint t, GLint r) );
    MOCK_METHOD2( gl_MultiTexCoord3iv, void  (GLenum target, const GLint * v) );
    MOCK_METHOD4( gl_MultiTexCoord3s, void  (GLenum target, GLshort s, GLshort t, GLshort r) );
    MOCK_METHOD2( gl_MultiTexCoord3sv, void  (GLenum target, const GLshort * v) );
    MOCK_METHOD5( gl_MultiTexCoord4d, void  (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q) );
    MOCK_METHOD2( gl_MultiTexCoord4dv, void  (GLenum target, const GLdouble * v) );
    MOCK_METHOD5( gl_MultiTexCoord4f, void  (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q) );
    MOCK_METHOD2( gl_MultiTexCoord4fv, void  (GLenum target, const GLfloat * v) );
    MOCK_METHOD5( gl_MultiTexCoord4i, void  (GLenum target, GLint s, GLint t, GLint r, GLint q) );
    MOCK_METHOD2( gl_MultiTexCoord4iv, void  (GLenum target, const GLint * v) );
    MOCK_METHOD5( gl_MultiTexCoord4s, void  (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q) );
    MOCK_METHOD2( gl_MultiTexCoord4sv, void  (GLenum target, const GLshort * v) );
    MOCK_METHOD2( gl_SampleCoverage, void  (GLclampf value, GLboolean invert) );
    MOCK_METHOD4( gl_BlendColor, void  (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha) );
    MOCK_METHOD1( gl_BlendEquation, void  (GLenum mode) );
    MOCK_METHOD4( gl_BlendFuncSeparate, void  (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha) );
    MOCK_METHOD3( gl_FogCoordPointer, void  (GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD1( gl_FogCoordd, void  (GLdouble coord) );
    MOCK_METHOD1( gl_FogCoorddv, void  (const GLdouble * coord) );
    MOCK_METHOD1( gl_FogCoordf, void  (GLfloat coord) );
    MOCK_METHOD1( gl_FogCoordfv, void  (const GLfloat * coord) );
    MOCK_METHOD4( gl_MultiDrawArrays, void  (GLenum mode, GLint * first, GLsizei * count, GLsizei primcount) );
    MOCK_METHOD5( gl_MultiDrawElements, void  (GLenum mode, GLsizei * count, GLenum type, const GLvoid ** indices, GLsizei primcount) );
    MOCK_METHOD2( gl_PointParameterf, void  (GLenum pname, GLfloat param) );
    MOCK_METHOD2( gl_PointParameterfv, void  (GLenum pname, const GLfloat * params) );
    MOCK_METHOD2( gl_PointParameteri, void  (GLenum pname, GLint param) );
    MOCK_METHOD2( gl_PointParameteriv, void  (GLenum pname, const GLint * params) );
    MOCK_METHOD3( gl_SecondaryColor3b, void  (GLbyte red, GLbyte green, GLbyte blue) );
    MOCK_METHOD1( gl_SecondaryColor3bv, void  (const GLbyte * v) );
    MOCK_METHOD3( gl_SecondaryColor3d, void  (GLdouble red, GLdouble green, GLdouble blue) );
    MOCK_METHOD1( gl_SecondaryColor3dv, void  (const GLdouble * v) );
    MOCK_METHOD3( gl_SecondaryColor3f, void  (GLfloat red, GLfloat green, GLfloat blue) );
    MOCK_METHOD1( gl_SecondaryColor3fv, void  (const GLfloat * v) );
    MOCK_METHOD3( gl_SecondaryColor3i, void  (GLint red, GLint green, GLint blue) );
    MOCK_METHOD1( gl_SecondaryColor3iv, void  (const GLint * v) );
    MOCK_METHOD3( gl_SecondaryColor3s, void  (GLshort red, GLshort green, GLshort blue) );
    MOCK_METHOD1( gl_SecondaryColor3sv, void  (const GLshort * v) );
    MOCK_METHOD3( gl_SecondaryColor3ub, void  (GLubyte red, GLubyte green, GLubyte blue) );
    MOCK_METHOD1( gl_SecondaryColor3ubv, void  (const GLubyte * v) );
    MOCK_METHOD3( gl_SecondaryColor3ui, void  (GLuint red, GLuint green, GLuint blue) );
    MOCK_METHOD1( gl_SecondaryColor3uiv, void  (const GLuint * v) );
    MOCK_METHOD3( gl_SecondaryColor3us, void  (GLushort red, GLushort green, GLushort blue) );
    MOCK_METHOD1( gl_SecondaryColor3usv, void  (const GLushort * v) );
    MOCK_METHOD4( gl_SecondaryColorPointer, void  (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD2( gl_WindowPos2d, void  (GLdouble x, GLdouble y) );
    MOCK_METHOD1( gl_WindowPos2dv, void  (const GLdouble * p) );
    MOCK_METHOD2( gl_WindowPos2f, void  (GLfloat x, GLfloat y) );
    MOCK_METHOD1( gl_WindowPos2fv, void  (const GLfloat * p) );
    MOCK_METHOD2( gl_WindowPos2i, void  (GLint x, GLint y) );
    MOCK_METHOD1( gl_WindowPos2iv, void  (const GLint * p) );
    MOCK_METHOD2( gl_WindowPos2s, void  (GLshort x, GLshort y) );
    MOCK_METHOD1( gl_WindowPos2sv, void  (const GLshort * p) );
    MOCK_METHOD3( gl_WindowPos3d, void  (GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD1( gl_WindowPos3dv, void  (const GLdouble * p) );
    MOCK_METHOD3( gl_WindowPos3f, void  (GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD1( gl_WindowPos3fv, void  (const GLfloat * p) );
    MOCK_METHOD3( gl_WindowPos3i, void  (GLint x, GLint y, GLint z) );
    MOCK_METHOD1( gl_WindowPos3iv, void  (const GLint * p) );
    MOCK_METHOD3( gl_WindowPos3s, void  (GLshort x, GLshort y, GLshort z) );
    MOCK_METHOD1( gl_WindowPos3sv, void  (const GLshort * p) );
    MOCK_METHOD2( gl_BeginQuery, void  (GLenum target, GLuint id) );
    MOCK_METHOD2( gl_BindBuffer, void  (GLenum target, GLuint buffer) );
    MOCK_METHOD4( gl_BufferData, void  (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage) );
    MOCK_METHOD4( gl_BufferSubData, void  (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data) );
    MOCK_METHOD2( gl_DeleteBuffers, void  (GLsizei n, const GLuint * buffers) );
    MOCK_METHOD2( gl_DeleteQueries, void  (GLsizei n, const GLuint * ids) );
    MOCK_METHOD1( gl_EndQuery, void  (GLenum target) );
    MOCK_METHOD2( gl_GenBuffers, void  (GLsizei n, GLuint * buffers) );
    MOCK_METHOD2( gl_GenQueries, void  (GLsizei n, GLuint * ids) );
    MOCK_METHOD3( gl_GetBufferParameteriv, void  (GLenum target, GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetBufferPointerv, void  (GLenum target, GLenum pname, GLvoid ** params) );
    MOCK_METHOD4( gl_GetBufferSubData, void  (GLenum target, GLintptr offset, GLsizeiptr size, GLvoid * data) );
    MOCK_METHOD3( gl_GetQueryObjectiv, void  (GLuint id, GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetQueryObjectuiv, void  (GLuint id, GLenum pname, GLuint * params) );
    MOCK_METHOD3( gl_GetQueryiv, void  (GLenum target, GLenum pname, GLint * params) );
    MOCK_METHOD1( gl_IsBuffer, unsigned char  (GLuint buffer) );
    MOCK_METHOD1( gl_IsQuery, unsigned char  (GLuint id) );
    MOCK_METHOD2( gl_MapBuffer, void * (GLenum target, GLenum access) );
    MOCK_METHOD1( gl_UnmapBuffer, unsigned char  (GLenum target) );
    MOCK_METHOD2( gl_AttachShader, void  (GLuint program, GLuint shader) );
    MOCK_METHOD3( gl_BindAttribLocation, void  (GLuint program, GLuint index, const GLchar * name) );
    MOCK_METHOD2( gl_BlendEquationSeparate, void  (GLenum arg0, GLenum arg1) );
    MOCK_METHOD1( gl_CompileShader, void  (GLuint shader) );
    MOCK_METHOD0( gl_CreateProgram, unsigned int  () );
    MOCK_METHOD1( gl_CreateShader, unsigned int  (GLenum type) );
    MOCK_METHOD1( gl_DeleteProgram, void  (GLuint program) );
    MOCK_METHOD1( gl_DeleteShader, void  (GLuint shader) );
    MOCK_METHOD2( gl_DetachShader, void  (GLuint program, GLuint shader) );
    MOCK_METHOD1( gl_DisableVertexAttribArray, void  (GLuint arg0) );
    MOCK_METHOD2( gl_DrawBuffers, void  (GLsizei n, const GLenum * bufs) );
    MOCK_METHOD1( gl_EnableVertexAttribArray, void  (GLuint arg0) );
    MOCK_METHOD7( gl_GetActiveAttrib, void  (GLuint program, GLuint index, GLsizei maxLength, GLsizei * length, GLint * size, GLenum * type, GLchar * name) );
    MOCK_METHOD7( gl_GetActiveUniform, void  (GLuint program, GLuint index, GLsizei maxLength, GLsizei * length, GLint * size, GLenum * type, GLchar * name) );
    MOCK_METHOD4( gl_GetAttachedShaders, void  (GLuint program, GLsizei maxCount, GLsizei * count, GLuint * shaders) );
    MOCK_METHOD2( gl_GetAttribLocation, int  (GLuint program, const GLchar * name) );
    MOCK_METHOD4( gl_GetProgramInfoLog, void  (GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog) );
    MOCK_METHOD3( gl_GetProgramiv, void  (GLuint program, GLenum pname, GLint * param) );
    MOCK_METHOD4( gl_GetShaderInfoLog, void  (GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog) );
    MOCK_METHOD4( gl_GetShaderSource, void  (GLuint obj, GLsizei maxLength, GLsizei * length, GLchar * source) );
    MOCK_METHOD3( gl_GetShaderiv, void  (GLuint shader, GLenum pname, GLint * param) );
    MOCK_METHOD2( gl_GetUniformLocation, int  (GLuint program, const GLchar * name) );
    MOCK_METHOD3( gl_GetUniformfv, void  (GLuint program, GLint location, GLfloat * params) );
    MOCK_METHOD3( gl_GetUniformiv, void  (GLuint program, GLint location, GLint * params) );
    MOCK_METHOD3( gl_GetVertexAttribPointerv, void  (GLuint arg0, GLenum arg1, GLvoid ** arg2) );
    MOCK_METHOD3( gl_GetVertexAttribdv, void  (GLuint arg0, GLenum arg1, GLdouble * arg2) );
    MOCK_METHOD3( gl_GetVertexAttribfv, void  (GLuint arg0, GLenum arg1, GLfloat * arg2) );
    MOCK_METHOD3( gl_GetVertexAttribiv, void  (GLuint arg0, GLenum arg1, GLint * arg2) );
    MOCK_METHOD1( gl_IsProgram, unsigned char  (GLuint program) );
    MOCK_METHOD1( gl_IsShader, unsigned char  (GLuint shader) );
    MOCK_METHOD1( gl_LinkProgram, void  (GLuint program) );
    MOCK_METHOD4( gl_ShaderSource, void  (GLuint shader, GLsizei count, const GLchar ** strings, const GLint * lengths) );
    MOCK_METHOD4( gl_StencilFuncSeparate, void  (GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask) );
    MOCK_METHOD2( gl_StencilMaskSeparate, void  (GLenum arg0, GLuint arg1) );
    MOCK_METHOD4( gl_StencilOpSeparate, void  (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) );
    MOCK_METHOD2( gl_Uniform1f, void  (GLint location, GLfloat v0) );
    MOCK_METHOD3( gl_Uniform1fv, void  (GLint location, GLsizei count, const GLfloat * value) );
    MOCK_METHOD2( gl_Uniform1i, void  (GLint location, GLint v0) );
    MOCK_METHOD3( gl_Uniform1iv, void  (GLint location, GLsizei count, const GLint * value) );
    MOCK_METHOD3( gl_Uniform2f, void  (GLint location, GLfloat v0, GLfloat v1) );
    MOCK_METHOD3( gl_Uniform2fv, void  (GLint location, GLsizei count, const GLfloat * value) );
    MOCK_METHOD3( gl_Uniform2i, void  (GLint location, GLint v0, GLint v1) );
    MOCK_METHOD3( gl_Uniform2iv, void  (GLint location, GLsizei count, const GLint * value) );
    MOCK_METHOD4( gl_Uniform3f, void  (GLint location, GLfloat v0, GLfloat v1, GLfloat v2) );
    MOCK_METHOD3( gl_Uniform3fv, void  (GLint location, GLsizei count, const GLfloat * value) );
    MOCK_METHOD4( gl_Uniform3i, void  (GLint location, GLint v0, GLint v1, GLint v2) );
    MOCK_METHOD3( gl_Uniform3iv, void  (GLint location, GLsizei count, const GLint * value) );
    MOCK_METHOD5( gl_Uniform4f, void  (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) );
    MOCK_METHOD3( gl_Uniform4fv, void  (GLint location, GLsizei count, const GLfloat * value) );
    MOCK_METHOD5( gl_Uniform4i, void  (GLint location, GLint v0, GLint v1, GLint v2, GLint v3) );
    MOCK_METHOD3( gl_Uniform4iv, void  (GLint location, GLsizei count, const GLint * value) );
    MOCK_METHOD4( gl_UniformMatrix2fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix3fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix4fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD1( gl_UseProgram, void  (GLuint program) );
    MOCK_METHOD1( gl_ValidateProgram, void  (GLuint program) );
    MOCK_METHOD2( gl_VertexAttrib1d, void  (GLuint index, GLdouble x) );
    MOCK_METHOD2( gl_VertexAttrib1dv, void  (GLuint index, const GLdouble * v) );
    MOCK_METHOD2( gl_VertexAttrib1f, void  (GLuint index, GLfloat x) );
    MOCK_METHOD2( gl_VertexAttrib1fv, void  (GLuint index, const GLfloat * v) );
    MOCK_METHOD2( gl_VertexAttrib1s, void  (GLuint index, GLshort x) );
    MOCK_METHOD2( gl_VertexAttrib1sv, void  (GLuint index, const GLshort * v) );
    MOCK_METHOD3( gl_VertexAttrib2d, void  (GLuint index, GLdouble x, GLdouble y) );
    MOCK_METHOD2( gl_VertexAttrib2dv, void  (GLuint index, const GLdouble * v) );
    MOCK_METHOD3( gl_VertexAttrib2f, void  (GLuint index, GLfloat x, GLfloat y) );
    MOCK_METHOD2( gl_VertexAttrib2fv, void  (GLuint index, const GLfloat * v) );
    MOCK_METHOD3( gl_VertexAttrib2s, void  (GLuint index, GLshort x, GLshort y) );
    MOCK_METHOD2( gl_VertexAttrib2sv, void  (GLuint index, const GLshort * v) );
    MOCK_METHOD4( gl_VertexAttrib3d, void  (GLuint index, GLdouble x, GLdouble y, GLdouble z) );
    MOCK_METHOD2( gl_VertexAttrib3dv, void  (GLuint index, const GLdouble * v) );
    MOCK_METHOD4( gl_VertexAttrib3f, void  (GLuint index, GLfloat x, GLfloat y, GLfloat z) );
    MOCK_METHOD2( gl_VertexAttrib3fv, void  (GLuint index, const GLfloat * v) );
    MOCK_METHOD4( gl_VertexAttrib3s, void  (GLuint index, GLshort x, GLshort y, GLshort z) );
    MOCK_METHOD2( gl_VertexAttrib3sv, void  (GLuint index, const GLshort * v) );
    MOCK_METHOD2( gl_VertexAttrib4Nbv, void  (GLuint index, const GLbyte * v) );
    MOCK_METHOD2( gl_VertexAttrib4Niv, void  (GLuint index, const GLint * v) );
    MOCK_METHOD2( gl_VertexAttrib4Nsv, void  (GLuint index, const GLshort * v) );
    MOCK_METHOD5( gl_VertexAttrib4Nub, void  (GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w) );
    MOCK_METHOD2( gl_VertexAttrib4Nubv, void  (GLuint index, const GLubyte * v) );
    MOCK_METHOD2( gl_VertexAttrib4Nuiv, void  (GLuint index, const GLuint * v) );
    MOCK_METHOD2( gl_VertexAttrib4Nusv, void  (GLuint index, const GLushort * v) );
    MOCK_METHOD2( gl_VertexAttrib4bv, void  (GLuint index, const GLbyte * v) );
    MOCK_METHOD5( gl_VertexAttrib4d, void  (GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w) );
    MOCK_METHOD2( gl_VertexAttrib4dv, void  (GLuint index, const GLdouble * v) );
    MOCK_METHOD5( gl_VertexAttrib4f, void  (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) );
    MOCK_METHOD2( gl_VertexAttrib4fv, void  (GLuint index, const GLfloat * v) );
    MOCK_METHOD2( gl_VertexAttrib4iv, void  (GLuint index, const GLint * v) );
    MOCK_METHOD5( gl_VertexAttrib4s, void  (GLuint index, GLshort x, GLshort y, GLshort z, GLshort w) );
    MOCK_METHOD2( gl_VertexAttrib4sv, void  (GLuint index, const GLshort * v) );
    MOCK_METHOD2( gl_VertexAttrib4ubv, void  (GLuint index, const GLubyte * v) );
    MOCK_METHOD2( gl_VertexAttrib4uiv, void  (GLuint index, const GLuint * v) );
    MOCK_METHOD2( gl_VertexAttrib4usv, void  (GLuint index, const GLushort * v) );
    MOCK_METHOD6( gl_VertexAttribPointer, void  (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * pointer) );
    MOCK_METHOD4( gl_UniformMatrix2x3fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix2x4fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix3x2fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix3x4fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix4x2fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD4( gl_UniformMatrix4x3fv, void  (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) );
    MOCK_METHOD2( gl_BeginConditionalRender, void  (GLuint arg0, GLenum arg1) );
    MOCK_METHOD1( gl_BeginTransformFeedback, void  (GLenum arg0) );
    MOCK_METHOD3( gl_BindFragDataLocation, void  (GLuint arg0, GLuint arg1, const GLchar * arg2) );
    MOCK_METHOD2( gl_ClampColor, void  (GLenum arg0, GLenum arg1) );
    MOCK_METHOD4( gl_ClearBufferfi, void  (GLenum arg0, GLint arg1, GLfloat arg2, GLint arg3) );
    MOCK_METHOD3( gl_ClearBufferfv, void  (GLenum arg0, GLint arg1, const GLfloat * arg2) );
    MOCK_METHOD3( gl_ClearBufferiv, void  (GLenum arg0, GLint arg1, const GLint * arg2) );
    MOCK_METHOD3( gl_ClearBufferuiv, void  (GLenum arg0, GLint arg1, const GLuint * arg2) );
    MOCK_METHOD5( gl_ColorMaski, void  (GLuint arg0, GLboolean arg1, GLboolean arg2, GLboolean arg3, GLboolean arg4) );
    MOCK_METHOD2( gl_Disablei, void  (GLenum arg0, GLuint arg1) );
    MOCK_METHOD2( gl_Enablei, void  (GLenum arg0, GLuint arg1) );
    MOCK_METHOD0( gl_EndConditionalRender, void  () );
    MOCK_METHOD0( gl_EndTransformFeedback, void  () );
    MOCK_METHOD3( gl_GetBooleani_v, void  (GLenum arg0, GLuint arg1, GLboolean * arg2) );
    MOCK_METHOD2( gl_GetFragDataLocation, int  (GLuint arg0, const GLchar * arg1) );
    MOCK_METHOD2( gl_GetStringi, const unsigned char * (GLenum arg0, GLuint arg1) );
    MOCK_METHOD3( gl_GetTexParameterIiv, void  (GLenum arg0, GLenum arg1, GLint * arg2) );
    MOCK_METHOD3( gl_GetTexParameterIuiv, void  (GLenum arg0, GLenum arg1, GLuint * arg2) );
    MOCK_METHOD7( gl_GetTransformFeedbackVarying, void  (GLuint arg0, GLuint arg1, GLsizei arg2, GLsizei * arg3, GLsizei * arg4, GLenum * arg5, GLchar * arg6) );
    MOCK_METHOD3( gl_GetUniformuiv, void  (GLuint arg0, GLint arg1, GLuint * arg2) );
    MOCK_METHOD3( gl_GetVertexAttribIiv, void  (GLuint arg0, GLenum arg1, GLint * arg2) );
    MOCK_METHOD3( gl_GetVertexAttribIuiv, void  (GLuint arg0, GLenum arg1, GLuint * arg2) );
    MOCK_METHOD2( gl_IsEnabledi, unsigned char  (GLenum arg0, GLuint arg1) );
    MOCK_METHOD3( gl_TexParameterIiv, void  (GLenum arg0, GLenum arg1, const GLint * arg2) );
    MOCK_METHOD3( gl_TexParameterIuiv, void  (GLenum arg0, GLenum arg1, const GLuint * arg2) );
    MOCK_METHOD4( gl_TransformFeedbackVaryings, void  (GLuint arg0, GLsizei arg1, const GLchar ** arg2, GLenum arg3) );
    MOCK_METHOD2( gl_Uniform1ui, void  (GLint arg0, GLuint arg1) );
    MOCK_METHOD3( gl_Uniform1uiv, void  (GLint arg0, GLsizei arg1, const GLuint * arg2) );
    MOCK_METHOD3( gl_Uniform2ui, void  (GLint arg0, GLuint arg1, GLuint arg2) );
    MOCK_METHOD3( gl_Uniform2uiv, void  (GLint arg0, GLsizei arg1, const GLuint * arg2) );
    MOCK_METHOD4( gl_Uniform3ui, void  (GLint arg0, GLuint arg1, GLuint arg2, GLuint arg3) );
    MOCK_METHOD3( gl_Uniform3uiv, void  (GLint arg0, GLsizei arg1, const GLuint * arg2) );
    MOCK_METHOD5( gl_Uniform4ui, void  (GLint arg0, GLuint arg1, GLuint arg2, GLuint arg3, GLuint arg4) );
    MOCK_METHOD3( gl_Uniform4uiv, void  (GLint arg0, GLsizei arg1, const GLuint * arg2) );
    MOCK_METHOD2( gl_VertexAttribI1i, void  (GLuint arg0, GLint arg1) );
    MOCK_METHOD2( gl_VertexAttribI1iv, void  (GLuint arg0, const GLint * arg1) );
    MOCK_METHOD2( gl_VertexAttribI1ui, void  (GLuint arg0, GLuint arg1) );
    MOCK_METHOD2( gl_VertexAttribI1uiv, void  (GLuint arg0, const GLuint * arg1) );
    MOCK_METHOD3( gl_VertexAttribI2i, void  (GLuint arg0, GLint arg1, GLint arg2) );
    MOCK_METHOD2( gl_VertexAttribI2iv, void  (GLuint arg0, const GLint * arg1) );
    MOCK_METHOD3( gl_VertexAttribI2ui, void  (GLuint arg0, GLuint arg1, GLuint arg2) );
    MOCK_METHOD2( gl_VertexAttribI2uiv, void  (GLuint arg0, const GLuint * arg1) );
    MOCK_METHOD4( gl_VertexAttribI3i, void  (GLuint arg0, GLint arg1, GLint arg2, GLint arg3) );
    MOCK_METHOD2( gl_VertexAttribI3iv, void  (GLuint arg0, const GLint * arg1) );
    MOCK_METHOD4( gl_VertexAttribI3ui, void  (GLuint arg0, GLuint arg1, GLuint arg2, GLuint arg3) );
    MOCK_METHOD2( gl_VertexAttribI3uiv, void  (GLuint arg0, const GLuint * arg1) );
    MOCK_METHOD2( gl_VertexAttribI4bv, void  (GLuint arg0, const GLbyte * arg1) );
    MOCK_METHOD5( gl_VertexAttribI4i, void  (GLuint arg0, GLint arg1, GLint arg2, GLint arg3, GLint arg4) );
    MOCK_METHOD2( gl_VertexAttribI4iv, void  (GLuint arg0, const GLint * arg1) );
    MOCK_METHOD2( gl_VertexAttribI4sv, void  (GLuint arg0, const GLshort * arg1) );
    MOCK_METHOD2( gl_VertexAttribI4ubv, void  (GLuint arg0, const GLubyte * arg1) );
    MOCK_METHOD5( gl_VertexAttribI4ui, void  (GLuint arg0, GLuint arg1, GLuint arg2, GLuint arg3, GLuint arg4) );
    MOCK_METHOD2( gl_VertexAttribI4uiv, void  (GLuint arg0, const GLuint * arg1) );
    MOCK_METHOD2( gl_VertexAttribI4usv, void  (GLuint arg0, const GLushort * arg1) );
    MOCK_METHOD5( gl_VertexAttribIPointer, void  (GLuint arg0, GLint arg1, GLenum arg2, GLsizei arg3, const GLvoid * arg4) );
    MOCK_METHOD4( gl_DrawArraysInstanced, void  (GLenum arg0, GLint arg1, GLsizei arg2, GLsizei arg3) );
    MOCK_METHOD5( gl_DrawElementsInstanced, void  (GLenum arg0, GLsizei arg1, GLenum arg2, const GLvoid * arg3, GLsizei arg4) );
    MOCK_METHOD1( gl_PrimitiveRestartIndex, void  (GLuint arg0) );
    MOCK_METHOD3( gl_TexBuffer, void  (GLenum arg0, GLenum arg1, GLuint arg2) );
    MOCK_METHOD4( gl_FramebufferTexture, void  (GLenum arg0, GLenum arg1, GLuint arg2, GLint arg3) );
    MOCK_METHOD3( gl_GetBufferParameteri64v, void  (GLenum arg0, GLenum arg1, GLint64 * arg2) );
    MOCK_METHOD3( gl_GetInteger64i_v, void  (GLenum arg0, GLuint arg1, GLint64 * arg2) );
    MOCK_METHOD2( gl_VertexAttribDivisor, void  (GLuint index, GLuint divisor) );
    MOCK_METHOD3( gl_BlendEquationSeparatei, void  (GLuint buf, GLenum modeRGB, GLenum modeAlpha) );
    MOCK_METHOD2( gl_BlendEquationi, void  (GLuint buf, GLenum mode) );
    MOCK_METHOD5( gl_BlendFuncSeparatei, void  (GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) );
    MOCK_METHOD3( gl_BlendFunci, void  (GLuint buf, GLenum src, GLenum dst) );
    MOCK_METHOD1( gl_MinSampleShading, void  (GLclampf value) );
    MOCK_METHOD2( gl_BindBufferARB, void  (GLenum target, GLuint buffer) );
    MOCK_METHOD4( gl_BufferDataARB, void  (GLenum target, GLsizeiptrARB size, const GLvoid * data, GLenum usage) );
    MOCK_METHOD4( gl_BufferSubDataARB, void  (GLenum target, GLintptrARB offset, GLsizeiptrARB size, const GLvoid * data) );
    MOCK_METHOD2( gl_DeleteBuffersARB, void  (GLsizei n, const GLuint * buffers) );
    MOCK_METHOD2( gl_GenBuffersARB, void  (GLsizei n, GLuint * buffers) );
    MOCK_METHOD3( gl_GetBufferParameterivARB, void  (GLenum target, GLenum pname, GLint * params) );
    MOCK_METHOD3( gl_GetBufferPointervARB, void  (GLenum target, GLenum pname, GLvoid ** params) );
    MOCK_METHOD4( gl_GetBufferSubDataARB, void  (GLenum target, GLintptrARB offset, GLsizeiptrARB size, GLvoid * data) );
    MOCK_METHOD1( gl_IsBufferARB, unsigned char  (GLuint buffer) );
    MOCK_METHOD2( gl_MapBufferARB, void * (GLenum target, GLenum access) );
    MOCK_METHOD1( gl_UnmapBufferARB, unsigned char  (GLenum target) );
    MOCK_METHOD1( glew_IsSupported, GLboolean (const char * name) );
    MOCK_METHOD1( glew_GetExtension, GLboolean (const char * name) );
    MOCK_METHOD1( glew_GetErrorString, const GLubyte * (GLenum error) );
    MOCK_METHOD1( glew_GetString, const GLubyte * (GLenum name) );
};
#endif /* __GLMOCK_HPP__ */
